name: Bug Report
description: Create a report to help us improve Sketchware Pro.
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the Bug
      description: Please give us a clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the behavior
      description: Please give us steps to reproduce the behavior
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
